In [7]:
# Data Analysis With Python Pandas ----- Employee Salary  DataSet
import pandas as pd
import numpy as np
pd.set_option("display.max_columns",None)
df=pd.read_csv("G:\\NareshIT\\Python\\11amNumpyExamples\\Pandas\\EDA_Empoloyee_Salary_Analysis_Project\\Salaries.csv")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [ ]:
for records in df.iterrows():
    print(records)

(0, Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object)
(1, Id                                                2
EmployeeName                           GARY JIMENEZ
JobTitle            CAPTAIN III (POLICE DEPARTMENT)
BasePay                                   155966.02
OvertimePay                               245131.88
OtherPay                                  137811.38
Benefits                                        NaN
TotalPay                                  538909.28
TotalPayBenefits                          538909.28
Year                                           2011
Notes                                           NaN
Agency                                San Francisco
Status                                          NaN
Name: 1, dtype: object)
(2, Id                                                3
EmployeeName                         ALBERT PARDINI
JobTitle            CAPTAIN III (POLICE DEPARTMENT)
BasePay                                   212739.13
OvertimePay                               106088.18
OtherPay                                    16452.6
Benefits                                        NaN
TotalPay                                  335279.91
TotalPayBenefits                          335279.91
Year                                           2011
Notes                                           NaN
Agency                                San Francisco
Status                                          NaN
Name: 2, dtype: object)
(3, Id                                                     4
EmployeeName                           CHRISTOPHER CHONG
JobTitle            WIRE ROPE CABLE MAINTENANCE MECHANIC
BasePay                                          77916.0
OvertimePay                                     56120.71
OtherPay                                        198306.9
Benefits                                             NaN
TotalPay                                       332343.61
TotalPayBenefits                               332343.61
Year                                                2011
Notes                                                NaN
Agency                                     San Francisco
Status                                               NaN
Name: 3, dtype: object)
(4, Id                                                             5
EmployeeName                                     PATRICK GARDNER
JobTitle            DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
BasePay                                                 134401.6
OvertimePay                                               9737.0
OtherPay                                               182234.59
Benefits                                                     NaN
TotalPay                                               326373.19
TotalPayBenefits                                       326373.19
Year                                                        2011
Notes                                                        NaN
Agency                                             San Francisco
Status                                                       NaN
Name: 4, dtype: object)
(5, Id                                          6
EmployeeName                   DAVID SULLIVAN
JobTitle            ASSISTANT DEPUTY CHIEF II
BasePay                              118602.0
OvertimePay                            8601.0
OtherPay                            189082.74
Benefits                                  NaN
TotalPay                            316285.74
TotalPayBenefits                    316285.74
Year                                     2011
Notes                                     NaN
Agency                          San Francisco
Status                                    NaN
Name: 5, dtype: object)
(6, Id                                                   7
EmployeeName                                 ALSON LEE
JobTitle            BATTALION CHIEF, (FIRE DEPARTMENT)
BasePay                                       92492.01
OvertimePay                                    89062.9
OtherPay                                     134426.14
Benefits                                           NaN
TotalPay                                     315981.05
TotalPayBenefits                             315981.05
Year                                              2011
Notes                                              NaN
Agency                                   San Francisco
Status                                             NaN
Name: 6, dtype: object)
(7, Id                                               8
EmployeeName                         DAVID KUSHNER
JobTitle            DEPUTY DIRECTOR OF INVESTMENTS
BasePay                                  256576.96
OvertimePay                                    0.0
OtherPay                                   51322.5
Benefits                                       NaN
TotalPay                                 307899.46
TotalPayBenefits                         307899.46
Year                                          2011
Notes                                          NaN
Agency                               San Francisco
Status                                         NaN
Name: 7, dtype: object)
(8, Id                                                   9
EmployeeName                            MICHAEL MORRIS
JobTitle            BATTALION CHIEF, (FIRE DEPARTMENT)
BasePay                                      176932.64
OvertimePay                                   86362.68
OtherPay                                      40132.23
Benefits                                           NaN
TotalPay                                     303427.55
TotalPayBenefits                             303427.55
Year                                              2011
Notes                                              NaN
Agency                                   San Francisco
Status                                             NaN
Name: 8, dtype: object)
(9, Id                                                      10
EmployeeName                            JOANNE HAYES-WHITE
JobTitle            CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
BasePay                                           285262.0
OvertimePay                                            0.0
OtherPay                                          17115.73
Benefits                                               NaN
TotalPay                                         302377.73
TotalPayBenefits                                 302377.73
Year                                                  2011
Notes                                                  NaN
Agency                                       San Francisco
Status                                                 NaN
Name: 9, dtype: object)
(10, Id                                                                11
EmployeeName                                           ARTHUR KENNEY
JobTitle            ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
BasePay                                                    194999.39
OvertimePay                                                 71344.88
OtherPay                                                     33149.9
Benefits                                                         NaN
TotalPay                                                   299494.17
TotalPayBenefits                                           299494.17
Year                                                            2011
Notes                                                            NaN
Agency                                                 San Francisco
Status                                                           NaN
Name: 10, dtype: object)
(11, Id                                               12
EmployeeName                       PATRICIA JACKSON
JobTitle            CAPTAIN III (POLICE DEPARTMENT)
BasePay                                     99722.0
OvertimePay                                87082.62
OtherPay                                   110804.3
Benefits                                        NaN
TotalPay                                  297608.92
TotalPayBenefits                          297608.92
Year                                           2011
Notes                                           NaN
Agency                                San Francisco
Status                                          NaN
Name: 11, dtype: object)
(12, Id                                           13
EmployeeName                  EDWARD HARRINGTON
JobTitle            EXECUTIVE CONTRACT EMPLOYEE
BasePay                               294580.02
OvertimePay                                 0.0
OtherPay                                    0.0
Benefits                                    NaN
TotalPay                              294580.02
TotalPayBenefits                      294580.02
Year                                       2011
Notes                                       NaN
Agency                            San Francisco
Status                                      NaN
Name: 12, dtype: object)
(13, Id                                 14
EmployeeName              JOHN MARTIN
JobTitle            DEPARTMENT HEAD V
BasePay                     271329.03
OvertimePay                       0.0
OtherPay                     21342.59
Benefits                          NaN
TotalPay                    292671.62
TotalPayBenefits            292671.62
Year                             2011
Notes                             NaN
Agency                  San Francisco
Status                            NaN
Name: 13, dtype: object)
(14, Id                                                  15
EmployeeName                            DAVID FRANKLIN
JobTitle            BATTALION CHIEF, (FIRE DEPARTMENT)
BasePay                                      174872.64
OvertimePay                                    74050.3
OtherPay                                      37424.11
Benefits                                           NaN
TotalPay                                     286347.05
TotalPayBenefits                             286347.05
Year                                              2011
Notes                                              NaN
Agency                                   San Francisco
Status                                             NaN
Name: 14, dtype: object)
(15, Id                                                  16
EmployeeName                           RICHARD CORRIEA
JobTitle            COMMANDER III, (POLICE DEPARTMENT)
BasePay                                      198778.01
OvertimePay                                    73478.2
OtherPay                                      13957.65
Benefits                                           NaN
TotalPay                                     286213.86
TotalPayBenefits                             286213.86
Year                                              2011
Notes                                              NaN
Agency                                   San Francisco
Status                                             NaN
Name: 15, dtype: object)
(16, Id                                 17
EmployeeName                 AMY HART
JobTitle            DEPARTMENT HEAD V
BasePay                     268604.57
OvertimePay                       0.0
OtherPay                     16115.86
Benefits                          NaN
TotalPay                    284720.43
TotalPayBenefits            284720.43
Year                             2011
Notes                             NaN
Agency                  San Francisco
Status                            NaN
Name: 16, dtype: object)
(17, Id                                                     18
EmployeeName                               SEBASTIAN WONG
JobTitle            CAPTAIN, EMERGENCYCY MEDICAL SERVICES
BasePay                                         140546.87
OvertimePay                                     119397.26
OtherPay                                         18625.08
Benefits                                              NaN
TotalPay                                        278569.21
TotalPayBenefits                                278569.21
Year                                                 2011
Notes                                                 NaN
Agency                                      San Francisco
Status                                                NaN
Name: 17, dtype: object)
(18, Id                                                  19
EmployeeName                                MARTY ROSS
JobTitle            BATTALION CHIEF, (FIRE DEPARTMENT)
BasePay                                      168692.63
OvertimePay                                   69626.12
OtherPay                                      38115.47
Benefits                                           NaN
TotalPay                                     276434.22
TotalPayBenefits                             276434.22
Year                                              2011
Notes                                              NaN
Agency                                   San Francisco
Status                                             NaN
Name: 18, dtype: object)
(19, Id                                          20
EmployeeName                     ELLEN MOFFATT
JobTitle            ASSISTANT MEDICAL EXAMINER
BasePay                              257510.59
OvertimePay                             880.16
OtherPay                               16159.5
Benefits                                   NaN
TotalPay                             274550.25
TotalPayBenefits                     274550.25
Year                                      2011
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 19, dtype: object)
(20, Id                                          21
EmployeeName                        VENUS AZAR
JobTitle            ASSISTANT MEDICAL EXAMINER
BasePay                              257510.48
OvertimePay                                0.0
OtherPay                              16679.79
Benefits                                   NaN
TotalPay                             274190.27
TotalPayBenefits                     274190.27
Year                                      2011
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 20, dtype: object)
(21, Id                                          22
EmployeeName                      JUDY MELINEK
JobTitle            ASSISTANT MEDICAL EXAMINER
BasePay                              257510.44
OvertimePay                             377.21
OtherPay                              15883.56
Benefits                                   NaN
TotalPay                             273771.21
TotalPayBenefits                     273771.21
Year                                      2011
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 21, dtype: object)
(22, Id                                         23
EmployeeName                    GEORGE GARCIA
JobTitle            CAPTAIN, FIRE SUPPRESSION
BasePay                             140546.88
OvertimePay                          93200.58
OtherPay                             39955.25
Benefits                                  NaN
TotalPay                            273702.71
TotalPayBenefits                    273702.71
Year                                     2011
Notes                                     NaN
Agency                          San Francisco
Status                                    NaN
Name: 22, dtype: object)
(23, Id                                                  24
EmployeeName                             VICTOR WYRSCH
JobTitle            BATTALION CHIEF, (FIRE DEPARTMENT)
BasePay                                      168692.63
OvertimePay                                   77896.14
OtherPay                                      24083.86
Benefits                                           NaN
TotalPay                                     270672.63
TotalPayBenefits                             270672.63
Year                                              2011
Notes                                              NaN
Agency                                   San Francisco
Status                                             NaN
Name: 23, dtype: object)
(24, Id                                         25
EmployeeName                  JOSEPH DRISCOLL
JobTitle            CAPTAIN, FIRE SUPPRESSION
BasePay                             140546.86
OvertimePay                          97868.77
OtherPay                             31909.28
Benefits                                  NaN
TotalPay                            270324.91
TotalPayBenefits                    270324.91
Year                                     2011
Notes                                     NaN
Agency                          San Francisco
Status                                    NaN
Name: 24, dtype: object)
(25, Id                               26
EmployeeName           GREGORY SUHR
JobTitle            CHIEF OF POLICE
BasePay                   256470.41
OvertimePay                     0.0
OtherPay                   11522.18
Benefits                        NaN
TotalPay                  267992.59
TotalPayBenefits          267992.59
Year                           2011
Notes                           NaN
Agency                San Francisco
Status                          NaN
Name: 25, dtype: object)
(26, Id                                         27
EmployeeName                      JOHN HANLEY
JobTitle            CAPTAIN, FIRE SUPPRESSION
BasePay                               92080.8
OvertimePay                           40008.0
OtherPay                            133695.76
Benefits                                  NaN
TotalPay                            265784.56
TotalPayBenefits                    265784.56
Year                                     2011
Notes                                     NaN
Agency                          San Francisco
Status                                    NaN
Name: 26, dtype: object)
(27, Id                                                  28
EmployeeName                            RAYMOND GUZMAN
JobTitle            BATTALION CHIEF, (FIRE DEPARTMENT)
BasePay                                      168692.59
OvertimePay                                   80706.88
OtherPay                                      16063.99
Benefits                                           NaN
TotalPay                                     265463.46
TotalPayBenefits                             265463.46
Year                                              2011
Notes                                              NaN
Agency                                   San Francisco
Status                                             NaN
Name: 27, dtype: object)
(28, Id                                                    29
EmployeeName                              DENISE SCHMITT
JobTitle            DEPUTY CHIEF III (POLICE DEPARTMENT)
BasePay                                         261717.6
OvertimePay                                          0.0

In [9]:
# dispaly top 10 rows of the dataset 
df.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [10]:
# 2 check last 10 rows of the dataset 
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [11]:
df[:10]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

In [12]:
len(df)

148654

In [13]:
df[len(df)-10:]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148645,148646,Carolyn A Wilson,Human Services Technician,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148648,148649,Leon Walker,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [14]:
len(df[len(df)-10:])

10

In [15]:
for ename in df[len(df)-10:]["EmployeeName"]:
    print(ename)

Randy D Winn
Carolyn A Wilson
Not provided
Joann Anderson
Leon Walker
Roy I Tillery
Not provided
Not provided
Not provided
Joe Lopez

In [16]:
# 3 find shape of our dataset (no of rows and columns)
df.shape

(148654, 13)

In [17]:
# 4 getting information about our dataset like total number rows,total number of column
# Datatypes of each column and requirement
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [19]:
# 5 ckeck Null Values in the Dataset
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [20]:
# 5 check Null Values in the dataset
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [22]:
# 6 Drop ID,Notes,Agency and status columns
# syntax: dataframe.drop(columns = ["col name1","colname2",.....],inplace = True)

df.drop(columns=["Id","Notes","Agency","Status"],inplace = True)
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014

In [23]:
df.shape

(148654, 9)

In [24]:
df.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [25]:
# 7 get overall statistical about the datframe 

df.describe() # or df.describe(include = "all") or df.describe(include = "object")

,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
mean,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

In [26]:
df.describe(include = "all")

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
unique,110811,2159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,13,7036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,NaN,NaN,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,NaN,NaN,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,NaN,NaN,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

In [27]:
df.describe(include = "object")

       EmployeeName          JobTitle
count        148654            148654
unique       110811              2159
top       Kevin Lee  Transit Operator
freq             13              7036

In [28]:
# 8 find occurence of the employee names (top 10) df["Employee Names"].value_counts()

df["EmployeeName"].value_counts().head(10)

EmployeeName
Kevin Lee       13
Richard Lee     11
Steven Lee      11
William Wong    11
Stanley Lee      9
KEVIN LEE        9
Michael Wong     9
John Chan        9
Victor Lee       8
DAVID WONG       8
Name: count, dtype: int64

In [29]:
# 9 find the number of unique of job titles

df["JobTitle"].nunique()

2159

In [30]:
# Extract Question.display the name of unique job titles

df["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], shape=(2159,), dtype=object)

In [31]:
# 10.total number of job titles contain
df[df["JobTitle"].str.contains("CAPTAINS")]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [32]:
df[df["JobTitle"].str.contains("CAPTAINS",case = False)]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [33]:
df[df["JobTitle"].str.contains("CAPTAINS",case=False)].count()

EmployeeName        0
JobTitle            0
BasePay             0
OvertimePay         0
OtherPay            0
Benefits            0
TotalPay            0
TotalPayBenefits    0
Year                0
dtype: int64

In [36]:
df[df["JobTitle"].str.contains("CAPTAIN",case=False)].count()

EmployeeName        552
JobTitle            552
BasePay             551
OvertimePay         552
OtherPay            552
Benefits            411
TotalPay            552
TotalPayBenefits    552
Year                552
dtype: int64

In [37]:
df[df["JobTitle"].str.contains("CAPTAIN",case=False)]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
116604,Gregory L Stewart,"Captain, Fire Suppression",73355.21,18517.18,49917.73,25608.77,141790.12,167398.89,2014
120867,Michael J Moran,Captain 3,7660.00,1496.09,126560.36,2189.51,135716.45,137905.96,2014
122361,Michael V Rolovich,"Captain, Fire Suppression",0.00,0.00,130320.75,0.00,130320.75,130320.75,2014
126588,Stephen M Tittel,Captain 3,68491.89,0.00,23721.91,19020.79,92213.80,111234.59,2014
132232,Jeanne M Seyler,"Captain, Fire Suppression",61039.43,2285.30,7548.29,20113.76,70873.02,90986.78,2014

In [38]:
len(df[df["JobTitle"].str.contains("CAPTAIN",case = False)])

552

In [39]:
df[df["JobTitle"].str.contains("CAPTAIN",case = False)].count()

EmployeeName        552
JobTitle            552
BasePay             551
OvertimePay         552
OtherPay            552
Benefits            411
TotalPay            552
TotalPayBenefits    552
Year                552
dtype: int64

In [40]:
# 11 display all the employee names  from fire department
df[df["JobTitle"].str.contains("fire",case = False)]['EmployeeName']

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: object

In [41]:
df["BasePay"].describe().agg(["max","mean","min"])

max     319275.010000
mean     96191.348042
min       -166.010000
Name: BasePay, dtype: float64

In [42]:
df[df["EmployeeName"]=="Not Provided"]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
13797,Not Provided,PUBLIC SAFETY COMMUNICATIONS DISPATCHER,57963.39,19683.91,4373.86,NaN,82021.16,82021.16,2011
44151,Not Provided,Public SafetyComm Disp,82196.52,25934.20,3752.49,38024.3,111883.21,149907.51,2012

In [45]:
df["EmployeeName"]=df["EmployeeName"].replace("Not Provided",np.nan)

In [46]:
df[df["EmployeeName"]=="Not Provided"]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [48]:
df.loc[44151]

EmployeeName                           NaN
JobTitle            Public SafetyComm Disp
BasePay                           82196.52
OvertimePay                        25934.2
OtherPay                           3752.49
Benefits                           38024.3
TotalPay                         111883.21
TotalPayBenefits                 149907.51
Year                                  2012
Name: 44151, dtype: object

In [49]:
#4 drop the rows having 4 missing values
df.isnull().sum(axis=1)==4 #---boolean array

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650     True
148651     True
148652     True
148653    False
Length: 148654, dtype: bool

In [50]:
df[df.isnull().sum(axis=1)==4]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
148646,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148650,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014

In [51]:
# df.drop(df[df.isnull().sum(axis=1)==5],axis = 0) --gives keyError
df.drop(df[df.isnull().sum(axis=1)==4].index,axis=0,inplace=True)

In [52]:
df[df.isnull().sum(axis=1)==4]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [53]:
len(df[df.isnull().sum(axis=1)==4])

0

In [ ]:
#15 find job title of ALBERT PARDINI
df[df["EmployeeName"]=="ALBERT PARDINI"]["JobTit"]